/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demomain;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dilsh
 */
public class AllCustomerReports extends javax.swing.JFrame {

    /**
     * Creates new form AllCustomerReports
     */
    public AllCustomerReports() {
        initComponents();
        loading2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAllcustomerreport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Customer Reports");

        Btnback.setBackground(new java.awt.Color(255, 51, 0));
        Btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnback.setForeground(new java.awt.Color(255, 255, 255));
        Btnback.setText("Back");
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });

        TblAllcustomerreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "XS", "S", "M", "L", "XL", "XXL", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblAllcustomerreport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        dispose();
        ViewReports cc =new ViewReports();
        cc.setVisible(true);
    }//GEN-LAST:event_BtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCustomerReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnback;
    private javax.swing.JTable TblAllcustomerreport;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loading2() {
        
                DefaultTableModel mode2 = (DefaultTableModel) TblAllcustomerreport.getModel();
    
            String[] noDuplicate = {Fashionshop.list.get(0).getTelephone()};
        for (int i = 0; i < Fashionshop.list.size(); i++) {
            boolean isunique = false;
            loop:
            for (int j = 0; j < noDuplicate.length; j++) {

                if (Fashionshop.list.get(i).getTelephone().equals(noDuplicate[j])) {
                    isunique = false;
                    break loop;
                } else {
                    isunique = true;
                }

            }
            if (isunique) {
                String[] temp = new String[noDuplicate.length + 1];
                for (int k = 0; k < noDuplicate.length; k++) {
                    temp[k] = noDuplicate[k];
                }
                temp[temp.length - 1] = Fashionshop.list.get(i).getTelephone();
                noDuplicate = temp;
            }
        }

        int[] tempQts1 = new int[noDuplicate.length];
        int[] tempQts2 = new int[noDuplicate.length];
        int[] tempQts3 = new int[noDuplicate.length];
        int[] tempQts4 = new int[noDuplicate.length];
        int[] tempQts5 = new int[noDuplicate.length];
        int[] tempQts6 = new int[noDuplicate.length];
        int[] tempAmount3 = new int[noDuplicate.length];

        for (int i = 0; i < noDuplicate.length; i++) {
            int sizeCount1 = 0, sizeCount2 = 0, sizeCount3 = 0, sizeCount4 = 0, sizeCount5 = 0, sizeCount6 = 0;
            int fullAmount = 0;

            for (int j = 0; j < Fashionshop.list.size(); j++) {
                if (Fashionshop.list.get(j).getTelephone().equals(noDuplicate[i])) {

                    fullAmount += Fashionshop.list.get(j).getAmount();

                    if (Fashionshop.list.get(j).getSizes().equals("XS")) {

                        sizeCount1 += Fashionshop.list.get(j).getQts();

                    }
                    if (Fashionshop.list.get(j).getSizes().equals("S")) {

                        sizeCount2 += Fashionshop.list.get(j).getQts();

                    }
                    if (Fashionshop.list.get(j).getSizes().equals("M")) {

                        sizeCount3 += Fashionshop.list.get(j).getQts();

                    }
                    if (Fashionshop.list.get(j).getSizes().equals("L")) {

                        sizeCount4 += Fashionshop.list.get(j).getQts();

                    }
                    if (Fashionshop.list.get(j).getSizes().equals("XL")) {

                        sizeCount5 += Fashionshop.list.get(j).getQts();

                    }
                    if (Fashionshop.list.get(j).getSizes().equals("XXL")) {

                        sizeCount6 += Fashionshop.list.get(j).getQts();

                    }

                }

                tempAmount3[i] = fullAmount;
                tempQts1[i] = sizeCount1;
                tempQts2[i] = sizeCount2;
                tempQts3[i] = sizeCount3;
                tempQts4[i] = sizeCount4;
                tempQts5[i] = sizeCount5;
                tempQts6[i] = sizeCount6;
            }

        }
         mode2.setRowCount(0);
        for (int i = 0; i < noDuplicate.length; i++) {
            mode2.addRow(new Object[]{noDuplicate[i],tempQts1[i],tempQts2[i], tempQts3[i], tempQts4[i],tempQts5[i],tempQts6[i],tempAmount3[i]});  

        }



    }
}
