/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demomain;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dilsh
 */
public class PlaceOrder extends javax.swing.JFrame {

    private boolean textField1;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        GenerateId();
    }

    public String order;
    public String TeleNum;
    public String sizes;
    public int Qts;
    public int status;
    public int Amounts;
    public int price;
    public String amount1;

    public static int processing = 0;
    public static int Delevering = 1;
    public static int Delevered = 2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnpoBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputcustId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Inputsize = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        inputQty = new javax.swing.JTextField();
        place = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Place order");

        BtnpoBack.setBackground(new java.awt.Color(255, 0, 51));
        BtnpoBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnpoBack.setText("Back");
        BtnpoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpoBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Order Id               :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Customer Id        :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("  Size                      :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Qty                      :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Anount               :");

        inputcustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputcustIdActionPerformed(evt);
            }
        });

        Inputsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputsizeActionPerformed(evt);
            }
        });

        jLabel8.setText("(XS/S/M/L/XL/XXL)");

        Amount.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                AmountAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AmountKeyReleased(evt);
            }
        });

        lblOrderId.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblOrderIdAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        inputQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQtyActionPerformed(evt);
            }
        });
        inputQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputQtyKeyReleased(evt);
            }
        });

        place.setBackground(new java.awt.Color(102, 255, 102));
        place.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        place.setText("Place");
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnpoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Inputsize, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(inputcustId)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnpoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputcustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inputsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblOrderIdAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblOrderIdAncestorAdded
     order =lblOrderId.getText();
    

    }//GEN-LAST:event_lblOrderIdAncestorAdded

    private void AmountAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AmountAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountAncestorAdded

    private void inputcustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputcustIdActionPerformed
        TeleNum = inputcustId.getText();

        Inputsize.requestFocus();


    }//GEN-LAST:event_inputcustIdActionPerformed

    private void BtnpoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpoBackActionPerformed
        Fashionshop shop = new Fashionshop();
        shop.setVisible(true);
        count--;
        dispose();
    }//GEN-LAST:event_BtnpoBackActionPerformed

    private void InputsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputsizeActionPerformed
        sizes = Inputsize.getText().toUpperCase();

        inputQty.requestFocus();


    }//GEN-LAST:event_InputsizeActionPerformed

    private void inputQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQtyActionPerformed
        Qts = Integer.valueOf(inputQty.getText());

        place.requestFocus();

    }//GEN-LAST:event_inputQtyActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed

        TeleNum = inputcustId.getText();
       sizes = Inputsize.getText().toUpperCase();
        String Qts = inputQty.getText();

        if(sizes.isEmpty()||TeleNum.isEmpty()||Qts.isEmpty()){
        
          JOptionPane.showMessageDialog(this, "Empty Values Do Not Invalid !");
        
        }else{
        
        if (TeleNum.charAt(0) != '0' || TeleNum.length() != 10) {

            JOptionPane.showMessageDialog(this, "Invalid Phone Number !");
            //   inputcustId.requestFocus();
        } else {
            
            if (!sizes.equals("XS") && !sizes.equals("S") && !sizes.equals("M") && !sizes.equals("L") && !sizes.equals("XL") && !sizes.equals("XXL")) {

                JOptionPane.showMessageDialog(this, "Enter Correct Size !!");

            } else {
                
                int temp;
                temp = Integer.parseInt(Qts);
                if (temp > 0) {
                   Order or= new Order(lblOrderId.getText(),inputcustId.getText(),Inputsize.getText().toUpperCase(),Integer.parseInt(inputQty.getText()),0,Integer.parseInt(Amount.getText()));
                   
                    boolean added =Fashionshop.list.add(or);
                    if(added){
                     JOptionPane.showMessageDialog(this, "Order Placed");

                    }else{
                       JOptionPane.showMessageDialog(this, "Order Not Placed");

                    
                    }
                    
                    dispose();
                    
                    PlaceOrder ss = new PlaceOrder();
                    ss.setVisible(true);

                } else if (Qts.equals("")) {
                    JOptionPane.showMessageDialog(this, "Enter Valied Qty");
                } else {
                    JOptionPane.showMessageDialog(this, "Enter Valied Qty");

                }

            }
        }
        }


    }//GEN-LAST:event_placeActionPerformed

    private void inputQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQtyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQtyKeyPressed

    private void inputQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQtyKeyReleased
        sizes = Inputsize.getText().toUpperCase();
        Qts = Integer.parseInt(inputQty.getText());

        price = 0;
        if (sizes.equals("XS")) {

            price = 600 * Qts;

        }

        if (sizes.equals("S")) {
            price = 800 * Qts;

        }
        if (sizes.equals("M")) {
            price = 900 * Qts;

        }
        if (sizes.equals("L")) {
            price = 1000 * Qts;

        }

        if (sizes.equals("XL")) {
            price = 1100 * Qts;

        }

        if (sizes.equals("XXL")) {
            price = 1200 * Qts;

        }
        String amount1 = Integer.toString(price);

        Amount.setText(amount1);
    }//GEN-LAST:event_inputQtyKeyReleased

    private void AmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountKeyReleased
        Amount.setText(amount1);
    }//GEN-LAST:event_AmountKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }
    static int count = 0;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JButton BtnpoBack;
    private javax.swing.JTextField Inputsize;
    private javax.swing.JTextField inputQty;
    private javax.swing.JTextField inputcustId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JButton place;
    // End of variables declaration//GEN-END:variables

    private void GenerateId() {

        if (Fashionshop.list.size() > 0) {
            String lastID= Fashionshop.list.get(Fashionshop.list.size() - 1).getOrderid();
        int num=Integer.parseInt( lastID.split("#")[1]);
        num++;
        
        lblOrderId.setText(String.format("ODR#%06d", num));
        }
        else{
        lblOrderId.setText("ODR#000001");
        }
    }

}
