/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demomain;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dilsh
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btnback = new javax.swing.JButton();
        Btnviewcustomer = new javax.swing.JButton();
        Btnbestincustomer = new javax.swing.JButton();
        Btnallcustomer = new javax.swing.JButton();
        Btncategorizedbyqty = new javax.swing.JButton();
        Btncategorizedbyamount = new javax.swing.JButton();
        BtnOrderbyamount = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Reports");

        Btnback.setBackground(new java.awt.Color(255, 0, 0));
        Btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnback.setForeground(new java.awt.Color(255, 255, 255));
        Btnback.setText("Back");
        Btnback.setToolTipText("");
        Btnback.setBorderPainted(false);
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });

        Btnviewcustomer.setBackground(new java.awt.Color(51, 204, 0));
        Btnviewcustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnviewcustomer.setForeground(new java.awt.Color(255, 255, 255));
        Btnviewcustomer.setText("View Customer");
        Btnviewcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewcustomerActionPerformed(evt);
            }
        });

        Btnbestincustomer.setBackground(new java.awt.Color(51, 204, 0));
        Btnbestincustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnbestincustomer.setForeground(new java.awt.Color(255, 255, 255));
        Btnbestincustomer.setText("Best in Customer");
        Btnbestincustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbestincustomerActionPerformed(evt);
            }
        });

        Btnallcustomer.setBackground(new java.awt.Color(0, 204, 0));
        Btnallcustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnallcustomer.setForeground(new java.awt.Color(255, 255, 255));
        Btnallcustomer.setText("All Customer");
        Btnallcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnallcustomerActionPerformed(evt);
            }
        });

        Btncategorizedbyqty.setBackground(new java.awt.Color(0, 51, 255));
        Btncategorizedbyqty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btncategorizedbyqty.setForeground(new java.awt.Color(255, 255, 255));
        Btncategorizedbyqty.setText("Categorized By QTY");
        Btncategorizedbyqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncategorizedbyqtyActionPerformed(evt);
            }
        });

        Btncategorizedbyamount.setBackground(new java.awt.Color(51, 0, 255));
        Btncategorizedbyamount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btncategorizedbyamount.setForeground(new java.awt.Color(255, 255, 255));
        Btncategorizedbyamount.setText("Categorized By Amount");
        Btncategorizedbyamount.setBorderPainted(false);
        Btncategorizedbyamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncategorizedbyamountActionPerformed(evt);
            }
        });

        BtnOrderbyamount.setBackground(new java.awt.Color(102, 102, 102));
        BtnOrderbyamount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnOrderbyamount.setForeground(new java.awt.Color(255, 255, 255));
        BtnOrderbyamount.setText("Orders By Amount");
        BtnOrderbyamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderbyamountActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("All Orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btnviewcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnbestincustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(Btnallcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btncategorizedbyqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btncategorizedbyamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnOrderbyamount, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btncategorizedbyqty, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOrderbyamount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btnviewcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btnbestincustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btncategorizedbyamount, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)))
                .addComponent(Btnallcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtncategorizedbyamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncategorizedbyamountActionPerformed
        dispose();
        Bestsellingitemsortedbyamount jj = new Bestsellingitemsortedbyamount();
        jj.setVisible(true);
    }//GEN-LAST:event_BtncategorizedbyamountActionPerformed

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        dispose();
        Fashionshop ss = new Fashionshop();
        ss.setVisible(true);
    }//GEN-LAST:event_BtnbackActionPerformed

    private void BtnbestincustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbestincustomerActionPerformed
        dispose();
        
        BestInCustomer bb = new BestInCustomer();
        bb.setVisible(true);
  
    }//GEN-LAST:event_BtnbestincustomerActionPerformed

    private void BtnviewcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewcustomerActionPerformed
        dispose();
        ViewCustomer vv = new ViewCustomer();
        vv.setVisible(true);
    }//GEN-LAST:event_BtnviewcustomerActionPerformed

    private void BtnallcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnallcustomerActionPerformed
        dispose();
        AllCustomerReports zz = new AllCustomerReports();
        zz.setVisible(true);
    }//GEN-LAST:event_BtnallcustomerActionPerformed

    private void BtncategorizedbyqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncategorizedbyqtyActionPerformed
        dispose();
        Bestsellingcategoriessortedbyquantity nn = new Bestsellingcategoriessortedbyquantity();
        nn.setVisible(true);
    }//GEN-LAST:event_BtncategorizedbyqtyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        Allorders ss = new Allorders();
        ss.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnOrderbyamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderbyamountActionPerformed
        dispose();
        OrderByAmount hh = new OrderByAmount();
        hh.setVisible(true);
    }//GEN-LAST:event_BtnOrderbyamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOrderbyamount;
    private javax.swing.JButton Btnallcustomer;
    private javax.swing.JButton Btnback;
    private javax.swing.JButton Btnbestincustomer;
    private javax.swing.JButton Btncategorizedbyamount;
    private javax.swing.JButton Btncategorizedbyqty;
    private javax.swing.JButton Btnviewcustomer;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    public static String[] RemoveDuplicates() {
        
        int uniqueCount = 0;
        for (int i = 0; i < Fashionshop.list.size(); i++) {
            boolean unique = true;
            for (int j = i + 1; j < Fashionshop.list.size(); j++) {
                if (Fashionshop.list.get(i).getTelephone().equals(Fashionshop.list.get(j).getTelephone())) {
                    unique = false;
                    break;

                }

            }
            if (unique) {
                uniqueCount++;

            }

        }
        String [] noDuplicate = new String[uniqueCount];
        int currentindex = 0;
        
        for (int i = 0; i < Fashionshop.list.size(); i++) {
            boolean isunique =true;
            for (int j = 0; j < Fashionshop.list.size(); j++) {
              if(Fashionshop.list.get(i).getTelephone().equals(Fashionshop.list.get(j).getTelephone())){
              isunique = false;
              break;
              }
                
            }
            if(isunique){
            
            noDuplicate[currentindex++] =Fashionshop.list.get(i).getTelephone();
            }
            
        }
        return noDuplicate;
    }
}
